# Generated by Django 3.2.9 on 2022-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220305_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='alogin',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Pass', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
